#!/usr/bin/env python3
"""
Validation script for Interior Agent Bedrock integration
Tests the Bedrock Claude-based interior recommendation system
"""

import sys
import os
import json
from datetime import datetime

# Add shared modules to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src', 'lambda', 'shared'))
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src', 'lambda', 'agents', 'interior'))

def test_interior_bedrock_integration():
    """Test Interior Agent with Bedrock integration"""
    
    print("=" * 80)
    print("Interior Agent Bedrock Integration Validation")
    print("=" * 80)
    print()
    
    # Test 1: Import validation
    print("Test 1: Validating imports...")
    try:
        from index import InteriorAgent
        from shared.models import BusinessInfo
        print("✓ Imports successful")
    except ImportError as e:
        print(f"✗ Import failed: {str(e)}")
        return False
    
    # Test 2: Agent initialization
    print("\nTest 2: Initializing Interior Agent...")
    try:
        agent = InteriorAgent()
        print(f"✓ Agent initialized")
        print(f"  - Bedrock enabled: {agent.use_bedrock}")
        print(f"  - Bedrock client: {'Available' if agent.bedrock_client else 'Not available'}")
        print(f"  - Reasoning engine: {'Available' if agent.reasoning_engine else 'Not available'}")
    except Exception as e:
        print(f"✗ Agent initialization failed: {str(e)}")
        return False
    
    # Test 3: Business info creation
    print("\nTest 3: Creating test business info...")
    try:
        business_info = BusinessInfo(
            industry="restaurant",
            region="seoul",
            size="medium"
        )
        print("✓ Business info created")
        print(f"  - Industry: {business_info.industry}")
        print(f"  - Region: {business_info.region}")
        print(f"  - Size: {business_info.size}")
    except Exception as e:
        print(f"✗ Business info creation failed: {str(e)}")
        return False
    
    # Test 4: Bedrock recommendation generation (if Bedrock is available)
    if agent.use_bedrock and agent.bedrock_client:
        print("\nTest 4: Testing Bedrock-based interior recommendations...")
        try:
            session_id = f"test-session-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
            
            result = agent._generate_interior_recommendations_with_bedrock(
                session_id=session_id,
                business_info=business_info,
                selected_signboard=None
            )
            
            print("✓ Bedrock recommendations generated")
            print(f"  - Session ID: {result.get('sessionId')}")
            print(f"  - Total recommendations: {result.get('totalRecommendations')}")
            print(f"  - Confidence: {result.get('confidence', 0):.2f}")
            print(f"  - Generated by: {result.get('generatedBy')}")
            print(f"  - Latency: {result.get('latency_ms', 0)}ms")
            
            # Display recommendations
            recommendations = result.get('recommendations', [])
            for i, rec in enumerate(recommendations, 1):
                print(f"\n  Recommendation {i}:")
                print(f"    - Style: {rec.get('styleName', rec.get('style'))}")
                print(f"    - Suitability Score: {rec.get('suitabilityScore', 0):.1f}/100")
                print(f"    - Estimated Cost: {rec.get('estimatedCost')}")
                print(f"    - Description: {rec.get('description', '')[:100]}...")
            
            # Validate reasoning
            reasoning = result.get('reasoning', '')
            if reasoning:
                print(f"\n  Reasoning: {reasoning[:200]}...")
            
        except Exception as e:
            print(f"✗ Bedrock recommendation generation failed: {str(e)}")
            import traceback
            traceback.print_exc()
            return False
    else:
        print("\nTest 4: Skipped (Bedrock not available or disabled)")
        print("  - Set ENABLE_FALLBACK=false to enable Bedrock")
        print("  - Ensure AWS credentials are configured")
        print("  - Ensure Bedrock models are available in your region")
    
    # Test 5: Fallback recommendation generation
    print("\nTest 5: Testing fallback interior recommendations...")
    try:
        session_id = f"test-session-fallback-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
        
        result = agent._generate_interior_recommendations(
            session_id=session_id,
            business_info=business_info,
            selected_signboard=None
        )
        
        print("✓ Fallback recommendations generated")
        print(f"  - Session ID: {result.get('sessionId')}")
        print(f"  - Total recommendations: {result.get('totalRecommendations')}")
        print(f"  - Can proceed: {result.get('canProceed')}")
        
        # Display recommendations
        recommendations = result.get('recommendations', [])
        for i, rec in enumerate(recommendations, 1):
            print(f"\n  Recommendation {i}:")
            print(f"    - Style: {rec.get('styleName', rec.get('style'))}")
            print(f"    - Suitability Score: {rec.get('suitabilityScore', 0):.1f}/100")
            print(f"    - Estimated Cost: {rec.get('estimatedCost')}")
        
    except Exception as e:
        print(f"✗ Fallback recommendation generation failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return False
    
    # Test 6: Lambda handler integration
    print("\nTest 6: Testing Lambda handler...")
    try:
        event = {
            'body': json.dumps({
                'sessionId': f"test-lambda-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
                'businessInfo': {
                    'industry': 'cafe',
                    'region': 'busan',
                    'size': 'small'
                },
                'action': 'recommend'
            })
        }
        
        response = agent.execute(event, None)
        
        print("✓ Lambda handler executed")
        print(f"  - Status code: {response.get('statusCode')}")
        
        if response.get('statusCode') == 200:
            body = json.loads(response.get('body', '{}'))
            print(f"  - Recommendations: {body.get('totalRecommendations', 0)}")
            print(f"  - Generated by: {body.get('generatedBy', 'unknown')}")
        
    except Exception as e:
        print(f"✗ Lambda handler test failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return False
    
    print("\n" + "=" * 80)
    print("✓ All tests passed!")
    print("=" * 80)
    print()
    print("Summary:")
    print("- Interior Agent successfully integrated with Bedrock Claude")
    print("- Reasoning-based interior recommendations working")
    print("- Fallback mechanism operational")
    print("- Lambda handler integration verified")
    print()
    print("Next steps:")
    print("1. Deploy to AWS with 'sam build && sam deploy'")
    print("2. Test with real Bedrock API in AWS environment")
    print("3. Monitor CloudWatch logs for Bedrock API calls")
    print("4. Verify reasoning chain storage in DynamoDB")
    
    return True


if __name__ == "__main__":
    try:
        success = test_interior_bedrock_integration()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"\n✗ Validation failed with error: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
